version: "3.7"
services:
    app:
        build:
            args:
                user: Shawon
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: application
        container_name: application
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./.docker/app/php-fpm.ini:/usr/local/etc/php/conf.d/99-app.ini
        depends_on:
            - database
        links:
            - database
        networks:
            - network
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - ./:/var/www
            - ./.docker/nginx:/etc/nginx/conf.d/
        networks:
            - network
        depends_on:
            - database
            - phpmyadmin
    database:
        image: mysql:latest
        container_name: database
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - network
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        restart: always
        tty: true
        depends_on:
            - database
        ports:
            - "${PMA_PORT}:80"
        environment:
            PMA_HOST: database
            PMA_PORT: 3306
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            UPLOAD_LIMIT: 2048M
        networks:
            - network
    rabbitmq:
        image: rabbitmq:latest
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASSWORD: ${RABBITMQ_PASSWORD}
            RABBITMQ_DEFAULT_VHOST: /
            RABBITMQ_SSL_CACERTFILE: /rootCA.pem
            RABBITMQ_SSL_CERTFILE: /rootCA.pem
            RABBITMQ_SSL_KEYFILE: /rootCA.key
            RABBITMQ_SSL_VERIFY: verify_none
            RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT: "false"
        ports:
            - "${RABBITMQ_PORT}:5672"
        networks:
            - network
    rabbitmq-management:
        image: rabbitmq:management
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASSWORD: ${RABBITMQ_PASSWORD}
            RABBITMQ_DEFAULT_VHOST: /
            RABBITMQ_MANAGEMENT_SSL_CACERTFILE: /rootCA.pem
            RABBITMQ_MANAGEMENT_SSL_CERTFILE: /rootCA.pem
            RABBITMQ_MANAGEMENT_SSL_KEYFILE: /rootCA.key
            RABBITMQ_MANAGEMENT_SSL_VERIFY: verify_none
            RABBITMQ_MANAGEMENT_SSL_FAIL_IF_NO_PEER_CERT: "false"
        ports:
            - "15672:15672"
        networks:
            - network

networks:
    network:
        driver: bridge
